name: C/C++ CI

on:
  push:
    branches: [ raspberrypi-kernel_1.20210303-1-nand ]
  pull_request:
    branches: [ raspberrypi-kernel_1.20210303-1-nand ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init
      run: sudo apt-get update && sudo apt-get install gcc-9-arm-linux-gnueabihf gcc-arm-linux-gnueabihf lib32z1 lib32ncurses6 lib32stdc++6 lib32z1 lib32z1-dev
    - name: module.lds
      run: head -n 26 scripts/module.lds.S > scripts/module.lds
    - name: config
      run: wget https://gist.githubusercontent.com/TheCrazyT/31a64f4e3ee96566b1682d4b52e4e1db/raw/09d291f091415d68862f815c31c05880376df685/.config
    - name: Module.symvers
      run: make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules
 #     run: wget https://gist.githubusercontent.com/TheCrazyT/dbf9af02ec68b897c55d744705e358c6/raw/f0df9fc2af8262fb8e3938fa3955e4bb8af215c2/Module.symvers
    - name: prepare
      run: make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- oldconfig && make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- prepare
    - name: make misc
      run: export CURPWD=$PWD && cd drivers/misc/ && make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -C $CURPWD M=$PWD clean && ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make -C $CURPWD M=$PWD
    - name: make nand
      run: export CURPWD=$PWD && cd drivers/mtd/nand && make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -C $CURPWD M=$PWD clean && ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make KBUILD_EXTRA_SYMBOLS='${CURPWD}/Module.symvers' -C $CURPWD M=$PWD modules
    - name: find ko
      run: find -name "*.ko"
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: drivers/**/*.ko
