name: C/C++ CI

on:
  push:
    branches: [ raspberrypi-kernel_1.20210303-1-nand ]
  pull_request:
    branches: [ raspberrypi-kernel_1.20210303-1-nand ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init
      run: sudo apt-get install ncurses-dev make gcc-arm-linux-gnueabi
    - name: make misc
      run: export CURPWD=$PWD && cd drivers/misc/ && make -C $CURPWD M=$PWD clean && ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabi- make -C $CURPWD M=$PWD
    - name: make nand
      run: export CURPWD=$PWD && ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabi- make -C $CURPWD M=$PWD clean && ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabi- make KBUILD_EXTRA_SYMBOLS='$CURPWD/lib/Module.symvers' -C $CURPWD M=$PWD modules
