name: C/C++ CI

on:
  push:
    branches: [ raspberrypi-kernel_1.20210303-1-nand ]
  pull_request:
    branches: [ raspberrypi-kernel_1.20210303-1-nand ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init
      run: sudo apt-get install gcc-9-arm-linux-gnueabihf gcc-arm-linux-gnueabihf lib32z1 lib32ncurses6 lib32stdc++6 lib32z1 lib32z1-dev
    - name: prepare
      run: make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- oldconfig && make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- prepare
    - name: make misc
      run: export CURPWD=$PWD && cd drivers/misc/ && make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -C $CURPWD M=$PWD clean && ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make -C $CURPWD M=$PWD
    - name: make nand
      run: export CURPWD=$PWD && make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -C $CURPWD M=$PWD clean && ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make KBUILD_EXTRA_SYMBOLS='$CURPWD/lib/Module.symvers' -C $CURPWD M=$PWD modules
